# fly.toml app configuration file generated for hobbes-frontend on 2025-07-12T18:44:13+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hobbes-frontend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.production'
  [build.args]
    REACT_APP_API_URL = "https://hobbes-backend.fly.dev"
    REACT_APP_GOOGLE_CLIENT_ID = "775683774120-77a9d7tbo6s0n87op8cserkps28e6lq0.apps.googleusercontent.com"

[deploy]
  release_command = 'echo "Frontend starting..."'

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
