version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8888
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend/src:/code
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
      - DYNAMODB_ENDPOINT=http://dynamodb-local:7777
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -port 7777 -dbPath /home/dynamodblocal/data"
    ports:
      - "7777:7777"
    volumes:
      - ./.dynamodb:/home/dynamodblocal/data
    user: root

volumes:
  frontend_node_modules: 