# Fly.io configuration for Hobbes Backend
app = 'hobbes-backend'
primary_region = 'iad'  # Washington D.C. (us-east-1 equivalent)

[build]
  dockerfile = 'Dockerfile.production'

[env]
  # Environment will be set via 'fly secrets'
  ENVIRONMENT = 'production'
  AWS_REGION = 'us-east-1'
  
  # Database endpoints (production AWS)
  DYNAMODB_ENDPOINT = 'https://dynamodb.us-east-1.amazonaws.com'
  S3_ENDPOINT = 'https://s3.us-east-1.amazonaws.com'
  SQS_ENDPOINT = 'https://sqs.us-east-1.amazonaws.com'
  
  # SQS Queue
  AI_FILES_QUEUE_NAME = 'ai-files'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8888
  processes = ['app']

  [[services.ports]]
  port = 80
  handlers = ['http']
  force_https = true

  [[services.ports]]
  port = 443
  handlers = ['http', 'tls']

[deploy]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512 